repos:
- repo: local
  hooks:
  - id: ruff-check
    name: ruff-check
    entry: poetry run ruff check
    language: system
    types_or: [python, jupyter]
    stages: [pre-commit]

  - id: ruff-format
    name: ruff-format
    language: system
    entry: poetry run ruff format --check
    types_or: [python, jupyter]
    stages: [pre-commit]

  - id: pyright
    name: pyright
    language: system
    entry: poetry run pyright
    types: [python]
    pass_filenames: false

  - id: pytest
    name: pytest
    language: system
    entry: poetry run pytest
    types: [python]
    pass_filenames: false
    stages: [pre-push]
