services:

  web:
    build: .
    env_file:
      - .env
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
