"""Initial tender

Revision ID: 42ccf5b36691
Revises:
Create Date: 2025-01-23 09:08:09.693461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42ccf5b36691"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("publication_date", sa.DateTime(), nullable=False),
        sa.Column("buyer_name", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("regions", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("amount", sa.Double(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenders")
    # ### end Alembic commands ###
